### ISSUE TITLE
[Feature Request] `fal` should should support pre-hook python scripts 

### ISSUE THREAD

**Issue by turbo1912** [fal-ai/fal#107]
### Why are we doing this? 
Eventually we would like to enable adding python nodes to anywhere in a dbt dag, adding a pre-hook node is the best next step, and we already have users asking for it for simple EL use cases. 

Similar to the `fal run` command today, `fal` users should be able to write python scripts that are configured to run before a dbt run. 

Pre-hook scripts are called `before scripts` in `fal` terminology and marked as such in the configuration. 

*****

### For example: 

Given the following model configuration: 

```
models:
  - name: zendesk_ticket_descriptions
    description: zendesk ticket descriptions
    config:
      materialized: table
    meta:
      owner: "@meder"
      fal:
         scripts:
	        before:
	          - fal_scripts/postgres.py
	        after: // if there are no before scripts after can be omited 
	          - fal_scripts/slack.py
```

When the following command is invoked: 
```
fal run --before --select zendesk_ticket_descriptions
```
Then the following scripts are invoked: 
```
fal_scripts/postgres.py
```

`fal run --before` command does not add any artifact details to the context (let us know if this would be something useful)
