### ISSUE TITLE
fal: introduce fal.yaml

### ISSUE THREAD

**Issue by efiop** [fal-ai/fal#175]
E.g. something like having `fal.yaml` in your projects root with smth like this:
```
functions:
- name: FastSDXL
  module: fastsdxl.export
  alias: myfastsdxl
  auth: public
```

this could spare you remembering what apps you have and what commands to run to deploy them. And commands like fal fn run/serve (and I guess https://github.com/fal-ai/fal/pull/173 deploy?) could use it. Open to any suggestions on how it should look and what could include.
