### ISSUE TITLE
I would like to trigger fivetran and airbyte sync from fal

### ISSUE THREAD

**Issue by mkam039** [fal-ai/fal#179]
## New features requested:
- Ability to specify fivetran and airbyte (EL) connections in `profiles.yml`
- Magic functions for starting and checking sync operations

## Specifying EL connections in `profiles.yml`
```yaml
fal_test:
  target: dev
  fal:
    el:
      - type: fivetran
        api_key: my_fivetran_key
        api_secret: my_fivetran_secret
        connectors:
          - name: fivetran_connector_1
            id: id_fivetran_connector_1
          - name: fivetran_connector_2
            id: id_fivetran_connector_2
      - type: airbyte
        host: http://localhost:8001
        connections:
          - name: airbyte_connection_1
            id: id_airbyte_connection_1
          - name: airbyte_connection_2
            id: id_airbyte_connection_2
  outputs:
    dev:
      type: postgres
      host: localhost
      user: pguser
      password: pass
      port: 5432
      dbname: test
      schema: dbt_fal
      threads: 4
```

## Magic functions for sync operations
```python
# Starts airbyte sync and waits until it's completed
airbyte_sync(connection_id: str)
airbyte_sync_all()

# Starts fivtran sync and waits until it's completed
fivetran_sync(connector_id: str)
fivetran_sync_all()
```

These functions should also be available in FalDbt class:
```python
from fal import FalDbt
faldbt = FalDbt(profiles_dir="~/.dbt", project_dir="../my_project")

faldbt.airbyte_sync_all()
# etc
```

Alternatively, we could have a combined sync function:
```python
el_sync(el_type: str, connection_id: str, all: bool)
# el_type can be 'airbyte' or 'fivetran'
# connection_id and all are optional arguments, where either one or the other has to be provided.

faldbt.el_sync(el_type, connection_id)
```

**Comment by mkam039** [comment]
🙏 

- Yes, connections are for airbyte and connectors are for fivetran. Unifying it is an interesting idea. We would have to teach the users what definition would be though.
- I agree that being able to refer to connections by name would make it easier to work with them.

**Comment by chamini2** [comment]
You could want several Airbyte connections. I think we have to name a profile, like dbt names profiles (e.g. `dev` in your example profiles.yml)

```yaml
fal_test:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: pguser
      password: pass
      port: 5432
      dbname: test
      schema: dbt_fal
      threads: 4
  fal:
    el:
      my_fivetran:
        type: fivetran
        api_key: my_fivetran_key
        api_secret: my_fivetran_secret
        connectors:
          - name: fivetran_connector_1
            id: id_fivetran_connector_1
          - name: fivetran_connector_2
            id: id_fivetran_connector_2
      my_airbyte:
        type: airbyte
        host: http://localhost:8001
        connections:
          - name: airbyte_connection_1
            id: id_airbyte_connection_1
      my_other_airbyte:
        type: airbyte
        host: http://localhost:8002
        connections:
          - name: airbyte_connection_2
            id: id_airbyte_connection_2
```

This also makes me wonder about the need of the `el` property between `fal` and `my_fivetran`. Why would we need this and couldn't just list `my_fivetran` directly below `fal`?
