### ISSUE TITLE
Python after/before scripts should match how they are referenced in selection flags

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#292]
If we write in the yml file:

```yaml
models:
  - name: other_model
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/complete_other_model.py
```

Then to select said script it should be (with any graph operator)

```
--select fal_scripts/complete_other_model.py
```

Right now it works with

```
--select complete_other_model.py
```
