### ISSUE TITLE
Pure Python models design

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#301]
Introduce Python-only models to fal. This mirrors the dbt models for SQL. A Python model will _be_ a script with a call to `write_to_model` that creates the table in the database. Python models can be referenced from other dbt models as well as python models in the project using the ref function.

- Python models can be used interchangeably with any dbt model in the fal flow graph selectors
- Python models appear in the dbt lineage graph
- Python models can be documented the same way dbt models can in the schema.yml file

*****

Until now we have only attached Python scripts to existing SQL models and have done some creative workarounds to get the data back into the data warehouse. If we want to go closer to what seems to be the dbt ideas on how a transformation layer should work, we need to be able to create a new dbt model with the data from other models instead of modifying existing ones. Doing this enables us to be confident about parallelizations because no 2 scripts could be writing to the same model (race conditions).

# Previous work

Based on the [post from Andy Reagan](https://andyreagan.medium.com/non-sql-in-your-dbt-pipeline-c7cef2091619), we can see that if we generate a dbt model with

```sql
{{ config(materialized='ephemeral') }} 

/*
List your dbt dependencies here:

{{ ref('customers') }}
{{ ref('orders') }}
*/

select * {{ target.schema }}.{{ model.name }}
```

We can make dbt believe that the table is there and be able to reference it from other models ([read more on the ephemeral config](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/materializations#ephemeral) to understand how this hack works), while not really running the code for it.

# Proposal

The usage would be:

1. realize there are some Python scripts that are to be treated as models
  a. understand dependencies the Python script has to other models
2. write the ephemeral file for each of the models (with dependencies as a comment)
2. run the models
2. delete the ephemeral file for each of the models
  a. consider how this would affect `dbt docs`?

Let's assume the user has the following project

```
my_project/
├── dbt_project.yml
├── fal_scripts
│   └── after.py
└── models
    ├── some_model.sql
    ├── my_model.py
    └── schema.yml
```

Where the script looks like this:

> file `models/my_model.py`
```py
df = ref('some_model') # how do we realize there is a dependency?

s = source('app', 'a_source')

# use the df...

write_to_model(df)
```

### Mimic dbt

Leverage [the `model-paths` configuration](https://docs.getdbt.com/reference/project-configs/model-paths) to look for `.py` files and assume these are Python models.

The user would just write a model in one of the model paths.

CON: the user may have other `.py` files that should not be interpreted as models.

### Specify in the schema.yml

The user would be explicit about models fal should pick up:

> file `models/schema.yml`
```yaml
version: 2

models:
  - name: some_model
  - name: my_model
    meta:
      fal:
        model: true

sources:
  - name: app
    tables:
      - name: a_source
```

### Mimic dbt

We could do some parsing of the Python file. Probably very naive parsing is good enough for now.

### Specify in the schema.yml

A dependency could be specified in the `schema.yml`:

> file `models/schema.yml`
```yaml
version: 2

models:
  - name: some_model
  - name: my_model
    meta:
      fal:
        model: true
        deps:
          - ref('some_model')
          - source('app', 'a_source')

sources:
  - name: app
    tables:
      - name: a_source
```

*****

This is about FEA-20
