### ISSUE TITLE
Add the dbt target.name as a property on the context object

### ISSUE THREAD

**Issue by rudeb0y** [fal-ai/fal#535]
**Context**
I am sending slack messages and to keep things simple I have opted for one channel. (for some given set of models, that's handled through meta anyway i.e. slack_channel_id). 

However, doing this - it's hard to tell what the given environment was if you use one channel for all dbt invocations.

**Describe the solution you'd like**
I would like to be able to use context to access  dbt properties such as the target.name e.g.

```
    context.target.name # dev, test, prod, etc.
```
**Describe alternatives you've considered**
This can be worked around by injecting the {{ target.name }} as a meta field to a model.yml e.g:

```
version: 2

models:
  - name: my_funky_model
    meta:
      SLACK_CHANNEL_ID: XXXXXXXXXX
      TARGET: "{{ target.name }}"
      fal:
        scripts:
          - fal_scripts/notify_slack.py
```

However this does seem redundant/laborious to add to all .yml definitions
