### ISSUE TITLE
fal is not identifying correct model status: returning `success` instead of `error`

### ISSUE THREAD

**Issue by fredmny** [fal-ai/fal#541]
**Describe the bug**
fal is identifying a model that finished with an error on the dbt Cloud job as having the status `success`. 

We are running the  dbt job (cloud) with the Github Action from fal and aftewards running a script with `fal run` that checks all models (with `list_models()`) and sources (with `list_sources()`) and should send a Slack notification when a model finishes with an error or a model/source as a failed test. Unfortunately, even when the dbt job returns an error for a given model, fal returns a `success` in the `model.status` parameter (screenshots in the appropriate section below). We are also using the `dbt-artifacts` package and I checked the results there (to be sure it's not an issue with dbt's artifacts) and the model has the status `error` there.

The strange thing is: I created a faulty model to test the script and it worked well locally (identified the error and sent the Slack message). So I created a test job on dbt Cloud to reproduce what I was doing locally (running the faulty model on a test branch) and calling it with the same Github Action and it also did identify the faulty model and sent the Slack notification. So, here is what we have:

- fal script running as expected locally ✅ 
- fal script running as expected through Github Action with the test job on the test branch ✅ 
- fal script not identifying the model with error when running production job (with different error types) ❌ 

So, it's being hard to reproduce the error, but I will put the job configuration, as well as our Github workflow below to, maybe, help identify the problem.

**Your environment**
- OS: running on Github Action (Ubuntu)
- Paste the following commands output:
```
fal --version
0.5.2
dbt --version
Core :
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!
```
*also running 1.2 (latest) on Cloud*

- Adapter being used: spark

**How to reproduce**

**Expected behavior**
fal should identify models that ran with an error with status `error`

**Actual behavior**
fal is identifying models that ran with an error with status `success`

**Screenshots**
- Status being returned by dbt job:
<img width="805" alt="image (1)" src="https://user-images.githubusercontent.com/27257093/190461876-8b583b95-1229-46fd-9217-6fd982f095dd.png">

- Status being returned by fal:
<img width="549" alt="image (2)" src="https://user-images.githubusercontent.com/27257093/190462112-fcd5bc21-185d-4692-8aeb-4b9449008d13.png">

**Additional context**
- How we configure fal to be run
`schema.yml` file on root of `models` folder with following configuration:
```
version: 2

# Os arquivos schema.yml individuais estão em suas respectivas pastas
# Arquivo apenas para garantir a execução do script via fal, independente de quais modelos serão executados
fal:
  scripts:
    after:
      - fal_scripts/fal_notify_slack.py
```

- Github workflow file:
```
# Based on https://blog.fal.ai/how-to-run-python-with-dbt-cloud-hint-no-need-for-airflow/

name: Run Daily Production job on dbt Cloud
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.5

      - name: Install dependencies
        run: |
          sudo apt install libsasl2-dev
          poetry run pip install sasl
          poetry install
          poetry run pip install "dbt-spark[PyHive]"
      
      - uses: fal-ai/dbt-cloud-action@v3.3
        id: dbt_cloud_run
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ***
          dbt_cloud_job_id: ***

      - name: Run fal scripts
        if: always()
        env:
          ANALYTICS_NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.ANALYTICS_NOTIFICATION_SLACK_WEBHOOK_URL }}
          PROFILES_YML: ${{ secrets.PROFILES_YML }}
        run: |
          echo "$PROFILES_YML" >> profiles.yml
          poetry run dbt deps
          poetry run fal run --profiles-dir .
```

- dbt Production Job configuration
<img width="990" alt="image" src="https://user-images.githubusercontent.com/27257093/190463251-00d3711d-5802-4a2b-9ae7-9d576f7e5f6d.png">
