### ISSUE TITLE
Support trino in dbt fal

### ISSUE THREAD

**Issue by turbo1912** [fal-ai/fal#666]
**Context**
As a dbt-fal user, I would like to be able to run python models with fal while using the trino db

**Describe the solution you'd like**
This is already supported with fal CLI, so a similar approach would be suitable. 

https://github.com/fal-ai/fal/commit/d08d2242732a3000f8b4b18c7643f58884a0acea

**Is there an existing feature request for this?**
 * [ x]  I have searched the existing issues

**Comment by curiosityCursed** [comment]
Please do add support for trino db in dbt-fal.

**Comment by mederka** [comment]
Hey there @curiosityCursed! You can make dbt-fal work with trino if you install the dbt-trino adapter from their github repo: `pip install git+https://github.com/starburstdata/dbt-trino dbt-fal[trino]`. Here's what an example profiles.yml should look like:

```
fal_test:
  target: staging
  outputs:
    staging:
      type: fal
      db_profile: db
    db:
      type: trino
      user: user
      host: localhost
      port: 8080
      database: postgresql
      schema: dbt_fal
      threads: 8
      http_scheme: http
      session_properties:
        query_max_run_time: 5d
        exchange_compression: True
```
Let us know if you run into any issues!
