### ISSUE TITLE
fal should know about dbt Cloud Artifacts

### ISSUE THREAD

**Issue by burkaygur** [fal-ai/fal#79]
# DRAFT: fal dbt Cloud Specs

As of today, dbt cloud doesn't allow any external cli commands to be invoked other than dbt commands. This might be due to a few reasons including dbt labs wanting to keep dbt cloud as a secure environment that can only run known executables, difficulty of maintaining Python (or other languages) environments etc.

In order to run fal alongside dbt Cloud, we currently propose an approach where the invocation of **dbt Cloud Jobs** and fal happens from an external CI/CD system (Github Actions, Jenkins etc.). 

We recommend all dbt related commands to be configured within a **dbt Cloud Job**. The **Schedule** setting of the **Trigger** for these **Jobs** should be turned OFF, since we now have moved the scheduling responsibility to Github Actions. 

The fal team will provide a Github Action to trigger these jobs from within Github Actions easily. We then execute a `fal run` command to run the Python scripts. An example workflow could look like:

```yaml
 steps:
  - uses: actions/checkout@v2
  
  - uses: actions/setup-python@v2
     with:
       python-version: 3.7
  
  - name: Install dependencies
     run: |
       pip install -r requirements.txt
  
  - uses: fal-ai/fal-dbt-cloud@v1  # Exact name to be determined
     env:
       DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN }}   # This is to authenticate into dbt Cloud
       DBT_ACCOUNT_ID: 9876
     with:
       job-id: 1234 # This is the Job Id of the job that you want to trigger on dbt Cloud
     
     # This action outputs the run artifacts of this job
  
  - name: Run fal
    run: |
      fal run --profiles-dir . # fal reads the run artifacts from the previous step
```
