### ISSUE TITLE
Can one run `fal test`?

### ISSUE THREAD

**Issue by CavalcanteLucas** [fal-ai/fal#792]
I'm trying to make something like this:

```
fal test --profiles-dir . --target dev --selector my_data --vars '{my_var: "my_var_value"}'
```

Is it currently supported?

**Comment by chamini2** [comment]
Hello @CavalcanteLucas, thanks for reaching out. We currently don't have a `test` command. I am curious what would you expect a `fal test` command to do? Specifically, what would it do different than `dbt test`, for example?

**Comment by CavalcanteLucas** [comment]
Thank you for your quick answer @chamini2 

I wondered if the user could associate **fal** with dbt [tests](https://docs.getdbt.com/docs/build/tests). I assumed we could establish let's say a relationship test like:
 
```
version 2

models:
    - name: my_model
    - name: my_other_model
        columns:
            - name: my_model_id
                tests:
                    - relationships:
                        to: ref('my_model')
                        field: id
        meta:
            fal:
                scripts:
                    - fal_script.py
```

And, in case the test failed, **fal** would trigger the script that would send a slack message.

Is there maybe an alternative way to accomplish this?
